apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opa-polling
  labels:
    app: opa-polling
spec:
  to:
    kind: Service
    name: opa-polling
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
