apiVersion: v1
kind: Service
metadata:
  name: opa-polling
  labels:
    app: opa-polling
spec:
  selector:
    app: opa-polling
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
